[project]
name = "mldl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "sunwuk558@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.0.0",
    "pandas>=3.0.6",
]

[project.scripts]
mldl = "mldl:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
